package com.service;

import com.bean.OrderRecipients;

import java.util.List;

/**
 * @Author: zhuda
 * @Description:
 * @Date: Create in 8:48 2019/7/10
 */
public interface OrderRecipientsService {
    /**
     * 根据用户的id返回当前用户的收货人地址信息
     */
    List<OrderRecipients> selectOrderRecipientsByUserId(int userId);

    int insertSelective(OrderRecipients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recipientsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    int insert(OrderRecipients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    OrderRecipients selectByPrimaryKey(Integer recipientsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    List<OrderRecipients> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderRecipients record);

}
