package com.service;

import com.bean.Shopitems;

import java.util.List;
import java.util.Map;

/**
 * The interface Shopitems service.
 *
 * @Author: zhuda
 * @Description:
 * @Date: Create in 16:33 2019/7/7
 */
public interface ShopitemsService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param itemId the item id
     * @return the int
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int insert(Shopitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param itemId the item id
     * @return the shopitems
     * @mbg.generated
     */
    Shopitems selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @return the list
     * @mbg.generated
     */
    List<Shopitems> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int updateByPrimaryKey(Shopitems record);

    /**
     * 查询当前登陆用户的购物车集合对象信息
     *
     * @param usersid
     */
    List<Map<String, Object>> selectShopitemsByUsersId(int usersid);

    int updateNumByPrimaryKey(Shopitems record);

    List<Shopitems> selectByArrid(String ids, int i);


}
