package com.dao;

import com.bean.Admins;
import java.util.List;

public interface AdminsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    int insert(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    Admins selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    List<Admins> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Admins record);
}