package com.dao;

import com.bean.Funs;
import java.util.List;

public interface FunsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer funId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funs
     *
     * @mbg.generated
     */
    int insert(Funs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funs
     *
     * @mbg.generated
     */
    Funs selectByPrimaryKey(Integer funId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funs
     *
     * @mbg.generated
     */
    List<Funs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Funs record);
}