package com.dao;

import com.bean.Goods;
import java.util.List;

/**
 * The interface Goods mapper.
 */
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @param goodsId the goods id
     * @return the int
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @param goodsId the goods id
     * @return the goods
     * @mbg.generated
     */
    Goods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @return the list
     * @mbg.generated
     */
    List<Goods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int updateByPrimaryKey(Goods record);


    /**
     * Select by page list.
     *
     * @param startIndex the start index
     * @param pageCount  the page count
     * @return the list
     */
    List<Goods> selectByPage(int startIndex, int pageCount);

    /**
     * Select goods by key words list.
     *
     * @param keyWords the key words
     * @return the list
     */
    List<Goods> selectGoodsByName(String name);


}