package com.dao;

import com.bean.OrderDetail;
import java.util.List;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    OrderDetail selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    List<OrderDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderDetail record);

    List<OrderDetail> selectdetailId(String detailOrder);
}