package com.dao;

import com.bean.OrderRecipients;
import java.util.List;

public interface OrderRecipientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recipientsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    int insert(OrderRecipients record);

    int insertSelective(OrderRecipients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    OrderRecipients selectByPrimaryKey(Integer recipientsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    List<OrderRecipients> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_recipients
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderRecipients record);

    /**
     * 根据用户的id返回当前用户的收货人地址信息
     */
    List<OrderRecipients> selectOrderRecipientsByUserId(int userId);
}