package com.dao;

import com.bean.OrderStatus;
import java.util.List;

public interface OrderStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orderStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated
     */
    int insert(OrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated
     */
    OrderStatus selectByPrimaryKey(Integer orderStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated
     */
    List<OrderStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderStatus record);
}