package com.dao;

import com.bean.Orders;
import java.util.List;
import java.util.Map;

/**
 * The interface Orders mapper.
 */
public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @param orderId the order id
     * @return the int
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @param orderId the order id
     * @return the orders
     * @mbg.generated
     */
    Orders selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @return the list
     * @mbg.generated
     */
    List<Orders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int updateByPrimaryKey(Orders record);

    /**
     * Update status by id int.
     *
     * @param orders the orders
     * @return the int
     */
    int updateStatusById(Orders orders);

    /**
     * Select all orders by usersid list.
     *
     * @param usersid the usersid
     * @return the list
     */
    List<Map<String, Object>> selectAllOrdersByUsersid(int usersid);


    List<Map<String, Object>> selectWaitPayOrdersByUsersid(int usersid);

}