package com.dao;

import com.bean.Shopitems;
import java.util.List;
import java.util.Map;

/**
 * The interface Shopitems mapper.
 */
public interface ShopitemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param itemId the item id
     * @return the int
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int insert(Shopitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param itemId the item id
     * @return the shopitems
     * @mbg.generated
     */
    Shopitems selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @return the list
     * @mbg.generated
     */
    List<Shopitems> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopitems
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int updateByPrimaryKey(Shopitems record);

    /**
     * Update by primary key selective int.
     *
     * @param shopitems the shopitems
     * @return the int
     */
    int updateByPrimaryKeySelective(Shopitems shopitems);

    /***
     * 根据用户id和商品id查询是否操作这个购物车对象
     * @param record the record
     * @return shopitems
     */
    Shopitems selectByGoodsIdandUsersId(Shopitems record);

    /**
     * 查询当前登陆用户的购物车集合对象信息
     *
     * @param usersid the usersid
     * @return the list
     */
    List<Map<String, Object>> selectShopitemsByUsersId(int usersid);


    /**
     * 根据用户id及购物车id数组，获取购物车集合对象
     *
     * @param sid
     * @return
     */
    List<Map<String, Object>> selectShopitemsById(int usersid, String sid);


    List<Shopitems> selectByArrid(String ids,int i);

}