package com.bean;

public class Funs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funs.fun_id
     *
     * @mbg.generated
     */
    private Integer funId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funs.fun_name
     *
     * @mbg.generated
     */
    private String funName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funs.fun_url
     *
     * @mbg.generated
     */
    private String funUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funs.fun_pid
     *
     * @mbg.generated
     */
    private Integer funPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funs.fun_target
     *
     * @mbg.generated
     */
    private String funTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funs.fun_sort
     *
     * @mbg.generated
     */
    private Integer funSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funs.fun_id
     *
     * @return the value of funs.fun_id
     *
     * @mbg.generated
     */
    public Integer getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funs.fun_id
     *
     * @param funId the value for funs.fun_id
     *
     * @mbg.generated
     */
    public void setFunId(Integer funId) {
        this.funId = funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funs.fun_name
     *
     * @return the value of funs.fun_name
     *
     * @mbg.generated
     */
    public String getFunName() {
        return funName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funs.fun_name
     *
     * @param funName the value for funs.fun_name
     *
     * @mbg.generated
     */
    public void setFunName(String funName) {
        this.funName = funName == null ? null : funName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funs.fun_url
     *
     * @return the value of funs.fun_url
     *
     * @mbg.generated
     */
    public String getFunUrl() {
        return funUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funs.fun_url
     *
     * @param funUrl the value for funs.fun_url
     *
     * @mbg.generated
     */
    public void setFunUrl(String funUrl) {
        this.funUrl = funUrl == null ? null : funUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funs.fun_pid
     *
     * @return the value of funs.fun_pid
     *
     * @mbg.generated
     */
    public Integer getFunPid() {
        return funPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funs.fun_pid
     *
     * @param funPid the value for funs.fun_pid
     *
     * @mbg.generated
     */
    public void setFunPid(Integer funPid) {
        this.funPid = funPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funs.fun_target
     *
     * @return the value of funs.fun_target
     *
     * @mbg.generated
     */
    public String getFunTarget() {
        return funTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funs.fun_target
     *
     * @param funTarget the value for funs.fun_target
     *
     * @mbg.generated
     */
    public void setFunTarget(String funTarget) {
        this.funTarget = funTarget == null ? null : funTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funs.fun_sort
     *
     * @return the value of funs.fun_sort
     *
     * @mbg.generated
     */
    public Integer getFunSort() {
        return funSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funs.fun_sort
     *
     * @param funSort the value for funs.fun_sort
     *
     * @mbg.generated
     */
    public void setFunSort(Integer funSort) {
        this.funSort = funSort;
    }
}