package com.bean;

public class GoodsImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_img.img_id
     *
     * @mbg.generated
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_img.img_path
     *
     * @mbg.generated
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_img.img_goods
     *
     * @mbg.generated
     */
    private Integer imgGoods;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_img.img_id
     *
     * @return the value of goods_img.img_id
     *
     * @mbg.generated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_img.img_id
     *
     * @param imgId the value for goods_img.img_id
     *
     * @mbg.generated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_img.img_path
     *
     * @return the value of goods_img.img_path
     *
     * @mbg.generated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_img.img_path
     *
     * @param imgPath the value for goods_img.img_path
     *
     * @mbg.generated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_img.img_goods
     *
     * @return the value of goods_img.img_goods
     *
     * @mbg.generated
     */
    public Integer getImgGoods() {
        return imgGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_img.img_goods
     *
     * @param imgGoods the value for goods_img.img_goods
     *
     * @mbg.generated
     */
    public void setImgGoods(Integer imgGoods) {
        this.imgGoods = imgGoods;
    }
}