package com.bean;

public class OrderStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_status.order_status_id
     *
     * @mbg.generated
     */
    private Integer orderStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_status.order_status_name
     *
     * @mbg.generated
     */
    private String orderStatusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_status.order_status_id
     *
     * @return the value of order_status.order_status_id
     *
     * @mbg.generated
     */
    public Integer getOrderStatusId() {
        return orderStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_status.order_status_id
     *
     * @param orderStatusId the value for order_status.order_status_id
     *
     * @mbg.generated
     */
    public void setOrderStatusId(Integer orderStatusId) {
        this.orderStatusId = orderStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_status.order_status_name
     *
     * @return the value of order_status.order_status_name
     *
     * @mbg.generated
     */
    public String getOrderStatusName() {
        return orderStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_status.order_status_name
     *
     * @param orderStatusName the value for order_status.order_status_name
     *
     * @mbg.generated
     */
    public void setOrderStatusName(String orderStatusName) {
        this.orderStatusName = orderStatusName == null ? null : orderStatusName.trim();
    }
}