package com.bean;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_id
     *
     * @mbg.generated
     */
    private Integer detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_order
     *
     * @mbg.generated
     */
    private String detailOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_goods
     *
     * @mbg.generated
     */
    private Integer detailGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_price
     *
     * @mbg.generated
     */
    private Float detailPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_num
     *
     * @mbg.generated
     */
    private Integer detailNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.detail_id
     *
     * @return the value of order_detail.detail_id
     *
     * @mbg.generated
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.detail_id
     *
     * @param detailId the value for order_detail.detail_id
     *
     * @mbg.generated
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.detail_order
     *
     * @return the value of order_detail.detail_order
     *
     * @mbg.generated
     */
    public String getDetailOrder() {
        return detailOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.detail_order
     *
     * @param detailOrder the value for order_detail.detail_order
     *
     * @mbg.generated
     */
    public void setDetailOrder(String detailOrder) {
        this.detailOrder = detailOrder == null ? null : detailOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.detail_goods
     *
     * @return the value of order_detail.detail_goods
     *
     * @mbg.generated
     */
    public Integer getDetailGoods() {
        return detailGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.detail_goods
     *
     * @param detailGoods the value for order_detail.detail_goods
     *
     * @mbg.generated
     */
    public void setDetailGoods(Integer detailGoods) {
        this.detailGoods = detailGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.detail_price
     *
     * @return the value of order_detail.detail_price
     *
     * @mbg.generated
     */
    public Float getDetailPrice() {
        return detailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.detail_price
     *
     * @param detailPrice the value for order_detail.detail_price
     *
     * @mbg.generated
     */
    public void setDetailPrice(Float detailPrice) {
        this.detailPrice = detailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.detail_num
     *
     * @return the value of order_detail.detail_num
     *
     * @mbg.generated
     */
    public Integer getDetailNum() {
        return detailNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.detail_num
     *
     * @param detailNum the value for order_detail.detail_num
     *
     * @mbg.generated
     */
    public void setDetailNum(Integer detailNum) {
        this.detailNum = detailNum;
    }
}