package com.bean;

public class Permissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.permission_role
     *
     * @mbg.generated
     */
    private Integer permissionRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.permission_fun
     *
     * @mbg.generated
     */
    private Integer permissionFun;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.permission_role
     *
     * @return the value of permissions.permission_role
     *
     * @mbg.generated
     */
    public Integer getPermissionRole() {
        return permissionRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.permission_role
     *
     * @param permissionRole the value for permissions.permission_role
     *
     * @mbg.generated
     */
    public void setPermissionRole(Integer permissionRole) {
        this.permissionRole = permissionRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.permission_fun
     *
     * @return the value of permissions.permission_fun
     *
     * @mbg.generated
     */
    public Integer getPermissionFun() {
        return permissionFun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.permission_fun
     *
     * @param permissionFun the value for permissions.permission_fun
     *
     * @mbg.generated
     */
    public void setPermissionFun(Integer permissionFun) {
        this.permissionFun = permissionFun;
    }
}