package com.bean;

public class Shopitems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopitems.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopitems.item_goods
     *
     * @mbg.generated
     */
    private Integer itemGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopitems.item_price
     *
     * @mbg.generated
     */
    private Double itemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopitems.item_num
     *
     * @mbg.generated
     */
    private Integer itemNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopitems.item_user
     *
     * @mbg.generated
     */
    private Integer itemUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopitems.item_id
     *
     * @return the value of shopitems.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopitems.item_id
     *
     * @param itemId the value for shopitems.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopitems.item_goods
     *
     * @return the value of shopitems.item_goods
     *
     * @mbg.generated
     */
    public Integer getItemGoods() {
        return itemGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopitems.item_goods
     *
     * @param itemGoods the value for shopitems.item_goods
     *
     * @mbg.generated
     */
    public void setItemGoods(Integer itemGoods) {
        this.itemGoods = itemGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopitems.item_price
     *
     * @return the value of shopitems.item_price
     *
     * @mbg.generated
     */
    public Double getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopitems.item_price
     *
     * @param itemPrice the value for shopitems.item_price
     *
     * @mbg.generated
     */
    public void setItemPrice(Double itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopitems.item_num
     *
     * @return the value of shopitems.item_num
     *
     * @mbg.generated
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopitems.item_num
     *
     * @param itemNum the value for shopitems.item_num
     *
     * @mbg.generated
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopitems.item_user
     *
     * @return the value of shopitems.item_user
     *
     * @mbg.generated
     */
    public Integer getItemUser() {
        return itemUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopitems.item_user
     *
     * @param itemUser the value for shopitems.item_user
     *
     * @mbg.generated
     */
    public void setItemUser(Integer itemUser) {
        this.itemUser = itemUser;
    }

    @Override
    public String toString() {
        return "Shopitems{" +
                "itemId=" + itemId +
                ", itemGoods=" + itemGoods +
                ", itemPrice=" + itemPrice +
                ", itemNum=" + itemNum +
                ", itemUser=" + itemUser +
                '}';
    }
}